version: '1.0.0.{build}'

image: Visual Studio 2015

platform:
  - x64
 
configuration:
  - Release
  - Debug

environment:
  CMAKE_GENERATOR: "Visual Studio 14 2015 Win64" 
  VS: 2015
  #VCPKG_ARCH: x64-windows

init:
  - cmd: set PATH=%MINGW_DIR%;%PATH%

before_build:

install:
  - if "%VS%"=="2017" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if "%VS%"=="2015" call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%VS%"=="2015" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - cmake --version
  - set PATH=C:\Python38-x64;%PATH% &
    python -V &
    python -m pip install virtualenv wheel

build_script:
  - choco install swig --yes
  - choco install dos2unix --yes
  - echo %LD_LIBRARY_PATH%
  - swig -swiglib
  - echo %SWIG_LIB%
  - which cmake
  - mkdir install
  - mkdir build
  - cd build
  - pwd
  - cmake -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_VERBOSE_MAKEFILE=ON .. 
  - cmake --build . --config %configuration% --target install
  - set PYTHONPATH=%PYTHONPATH%;/c/Python38-x64/Lib/;/c/Python38-x64/DLLs/;%APPVEYOR_BUILD_FOLDER%\build\lib\
  - echo %PythonPath%
  - echo %PYTHONPATH%
  - set path=%PATH%;%PYTHONPATH%;
  - echo _gwblib > lib\gwb.pth
  - ls %APPVEYOR_BUILD_FOLDER%\build\
  - ls %APPVEYOR_BUILD_FOLDER%\build\lib\
  - ls /c/Python38-x64/Lib/
  - ls /c/Python38-x64/libs/
  - ls /c/Python38-x64/DLLs/

test_script: 
  - ctest -VV -C %configuration% -E _no_coordinates
after_test:
on_finish:
  - cat Testing/Temporary/LastTest.log

