name: github-docker

on: 
  push: 
    branches:
      - 'main'
  release:
    types: [published]

# If a merged PR triggers a rebuild of this docker image, and another
# PR is merged during the build, cancel the first of these since (i) this
# is a waste of time, and (ii) it creates a race condition with the
# upload.
concurrency:
  group: docker-build
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-docker:
    runs-on: ubuntu-latest
    if: github.repository == 'geodynamics/aspect'
    steps:    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_LOGIN }}

      - name: Build and push Docker image for main
        if: contains(github.event_name, 'push')
        uses: docker/build-push-action@v6
        with:
          context: ./contrib/docker/docker/
          cache-from: type=registry,ref=ubuntu:22.04
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ${{ github.repository }}:latest

      - name: Build and push Docker image for release
        if: contains(github.event_name, 'release')
        uses: docker/build-push-action@v6
        with:
          context: ./contrib/docker/docker/
          cache-from: type=registry,ref=ubuntu:22.04
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{github.ref_name}}
            ${{ github.repository }}:${{github.ref_name}}

  build-docker-tacc:
    runs-on: ubuntu-latest
    if: github.repository == 'geodynamics/aspect'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_LOGIN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for main
        if: contains(github.event_name, 'push')
        uses: docker/build-push-action@v6
        with:
          context: ./contrib/docker/docker_tacc/
          cache-from: type=registry,ref=ubuntu:22.04
          cache-to: type=inline
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest-tacc
            ${{ github.repository }}:latest-tacc

      - name: Build and push Docker image for release
        if: contains(github.event_name, 'release')
        uses: docker/build-push-action@v6
        with:
          context: ./contrib/docker/docker_tacc/
          cache-from: type=registry,ref=ubuntu:22.04
          cache-to: type=inline
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{github.ref_name}}-tacc
            ${{ github.repository }}:${{github.ref_name}}-tacc
